aws:
  s3:
    mock: false
spring:
  datasource:
    url: jdbc:postgresql://awseb-e-rqcwr2esna-stack-awsebrdsdatabase-uv53vamtxrqh.cqdw2tzunej9.ca-central-1.rds.amazonaws.com:5432/ebdb
    username: amigoscode
    password: password